import test from 'node:test';
import assert from 'node:assert/strict';
import {rankCoins,normalizeCoin,sortRows,safeUrl,selectContext,compareRows,categoryPayload} from '../src/lib/domain.js';
import {goldHistory,goldTrade,passports} from '../src/data/research.js';
const time=Date.parse('2026-09-13T12:00:00Z');
const coin=(id,cap,extra={})=>({id,name:`Asset ${id}`,symbol:`A${id}`,quote:{USD:{market_cap:cap,price:10,volume_24h:20,last_updated:new Date(time).toISOString()}},...extra});
test('dynamic top 3 and top 10 rank by cap, not list order',()=>{const coins=Array.from({length:12},(_,i)=>coin(i+1,(i+1)*100));assert.deepEqual(rankCoins(coins,3,time).rows.map(c=>c.id),[12,11,10]);assert.equal(rankCoins(coins,10,time).rows.length,10);});
test('denominator includes all eligible assets, not top 3',()=>{const ranked=rankCoins([coin(1,100),coin(2,100),coin(3,100),coin(4,100)],3,time);assert.equal(ranked.rows[0].share,25);assert.equal(ranked.total,400);});
test('missing cap is excluded rather than converted into zero',()=>{const ranked=rankCoins([coin(1,null),coin(2,0),coin(3,-1),coin(4,NaN),coin(5,30)],3,time);assert.equal(ranked.rows.length,1);assert.equal(ranked.excluded.unknown_market_cap,4);});
test('quotes must be fresh',()=>{const old=coin(1,100);old.quote.USD.last_updated='2020-01-01';assert.equal(normalizeCoin(old,time).reason,'stale_quote');});
test('future dated quotes are rejected',()=>{const future=coin(1,100);future.quote.USD.last_updated='2030-01-01';assert.equal(normalizeCoin(future,time).reason,'stale_quote');});
test('numeric strings are not silently trusted',()=>assert.equal(normalizeCoin(coin(1,'100'),time).reason,'unknown_market_cap'));
test('inactive and invalid IDs are rejected',()=>{assert.equal(normalizeCoin(coin(1,100,{is_active:0}),time).reason,'inactive');assert.equal(normalizeCoin(coin('1',100),time).reason,'invalid_id');});
test('stable ID tie-break and de-duplication',()=>{const ranked=rankCoins([coin(2,100),coin(1,100),coin(2,100)],3,time);assert.deepEqual(ranked.rows.map(c=>c.id),[1,2]);assert.equal(ranked.total,200);});
test('invalid ranking limits fail closed',()=>assert.throws(()=>rankCoins([],100,time)));
test('category supports documented map and observed object shapes',()=>{const value={coins:[],num_tokens:0};assert.equal(categoryPayload({data:value}),value);assert.equal(categoryPayload({data:{'1':value}}),value);assert.throws(()=>categoryPayload({data:{}}));});
test('only safe HTTPS sources are accepted',()=>{assert.equal(safeUrl('javascript:alert(1)'),null);assert.equal(safeUrl('file:///secret'),null);assert.equal(safeUrl('https://www.paxos.com/pax-gold'),'https://www.paxos.com/pax-gold');});
test('custody has no invented value or dominance',()=>{const context=selectContext(passports[0],'custody',goldHistory[2],goldTrade);assert.equal(context.kind,'qualitative');assert.equal(context.points[0].value,null);assert.equal(context.points[0].share,null);assert.equal(context.points[0].precision,'Region only');});
test('unknown equity custody stays unknown',()=>{const context=selectContext(passports[2],'custody',goldHistory[2],goldTrade);assert.equal(context.kind,'unknown');assert.deepEqual(context.points,[]);});
test('production is labeled commodity context and uses official unit',()=>{const context=selectContext(passports[0],'production',goldHistory[2],goldTrade);assert.equal(context.mode,'PUBLISHED_DATA');assert.equal(context.unit,'metric tonnes');assert.match(context.note,/Not the origin/);});
test('trade does not masquerade as token flows or shipping routes',()=>{const context=selectContext(passports[0],'trade',goldHistory[2],goldTrade);assert.equal(context.kind,'trade');assert.match(context.note,/not a token flow/);assert.equal(goldTrade.rows.reduce((sum,r)=>sum+r.value,0)+goldTrade.otherShare,100);});
test('official annual facts and revised vintage remain exact',()=>{assert.deepEqual(goldHistory.map(f=>f.rows.find(r=>r.id==='CHN').value),[375,377,380]);assert.deepEqual(goldHistory.map(f=>f.total),[3250,3280,3300]);assert.equal(goldHistory[2].rows.find(r=>r.id==='BRA').value,80);assert.equal(goldHistory[1].rows.find(r=>r.id==='AUS').value,284);});
test('history has stable cohort, not survivorship-biased current top 10',()=>{assert.deepEqual(goldHistory[0].rows.map(r=>r.id),goldHistory[2].rows.map(r=>r.id));assert.equal(goldHistory[2].rows.length,13);assert.equal(sortRows(goldHistory[2].rows).length,10);});
test('country share uses published rounded world total',()=>assert.equal(goldHistory[2].rows[0].share,380/3300*100));
test('missing historical comparison remains null',()=>assert.equal(compareRows([{id:'new',value:10}],[])[0].delta,null));
test('old custody statement retains original date',()=>assert.equal(passports[1].custody.sourceDate,'2020-01-23'));
