import {useMemo,useState} from 'react';
import {Play,Pause,ArrowSquareOut,Table,ChartBar} from '@phosphor-icons/react';
import {Chart} from './Chart.jsx';
import {sortRows,compareRows} from '../lib/domain.js';
import {goldHistory} from '../data/research.js';
import {atlasPalette as palette,atlasUiFont} from '../lib/atlas-theme.js';

export function Timeline({index,onIndex,playing,onPlay,compact=false}) {
  return <div className={`timeline ${compact?'compact':''}`}>
    <button className="play-button" aria-label={playing?'Pause history':'Play history'} onClick={onPlay}>{playing?<Pause weight="fill"/>:<Play weight="fill"/>}</button>
    <div className="time-track"><label htmlFor={compact?'year-compact':'year-full'}>Gold mine production <strong>{goldHistory[index].year}{index===2?' estimate':''}</strong></label><input id={compact?'year-compact':'year-full'} type="range" min="0" max="2" step="1" value={index} onChange={e=>onIndex(Number(e.target.value))}/><div className="time-labels">{goldHistory.map((f,i)=><button key={f.year} aria-label={`View ${f.year}`} aria-pressed={index===i} onClick={()=>onIndex(i)}>{f.year}</button>)}</div></div>
  </div>;
}
export function RaceChart({frame,selected,onSelect,reducedMotion,compact=false}) {
  const rows=frame.rows;
  const option=useMemo(()=>({animation:!reducedMotion,animationDuration:450,animationDurationUpdate:800,animationEasingUpdate:'cubicOut',aria:{enabled:true},grid:{left:compact?93:122,right:compact?44:72,top:12,bottom:12},xAxis:{type:'value',max:400,show:false},yAxis:{type:'category',inverse:true,max:compact?4:9,data:rows.map(r=>r.name),axisLine:{show:false},axisTick:{show:false},axisLabel:{color:palette.muted,fontFamily:atlasUiFont,fontSize:compact?12:14}},tooltip:{trigger:'item',renderMode:'richText',formatter:p=>`${p.name}: ${p.value} metric tonnes\nUSGS ${frame.year}${frame.year===2025?' estimate':''}`},series:[{id:'gold-production',type:'bar',realtimeSort:true,barWidth:compact?10:19,itemStyle:{borderRadius:2,borderColor:'#24545c',borderWidth:1},label:{show:true,position:'right',color:palette.ink,fontFamily:atlasUiFont,fontSize:compact?12:14,valueAnimation:!reducedMotion},data:rows.map(r=>({id:r.id,name:r.name,value:r.value,itemStyle:{color:r.id===selected?palette.gold:palette.teal}}))}]}),[frame,selected,reducedMotion,compact]);
  return <Chart className={compact?'race-chart compact':'race-chart'} option={option} onSelect={p=>onSelect(p.data.id)} label={`Gold mine production by country in ${frame.year}, measured in metric tonnes. Numeric values are also provided in the location list and analysis table.`}/>;
}
export default function History({asset,index,onIndex,playing,onPlay,selected,onSelect,reducedMotion,market,onShowWorld}) {
  const [metric,setMetric]=useState('production'),[showTable,setShowTable]=useState(false),[compare,setCompare]=useState(0),[marketIndex,setMarketIndex]=useState(0);
  const frame=goldHistory[index],previous=goldHistory[compare],compared=compareRows(sortRows(frame.rows),previous.rows),histories=market?.history||[],observation=histories[Math.min(marketIndex,histories.length-1)];
  return <section id="history" className="history-section"><div className="section-heading"><div><h2>A real asset has a history.</h2><p>Follow changing presence. Pause on the evidence.</p></div><div className="segmented" aria-label="History metric"><button aria-pressed={metric==='production'} onClick={()=>setMetric('production')}>Gold production</button><button aria-pressed={metric==='market'} onClick={()=>setMetric('market')}>Observed market cap</button></div></div>
    {metric==='production'?<div className="history-layout"><div className="history-chart-block"><div className="chart-heading"><div><strong>Leading gold-producing countries</strong><span>Metric tonnes · {frame.year}{frame.year===2025?' estimate':''}</span></div><button className="text-action" onClick={()=>setShowTable(v=>!v)}>{showTable?<ChartBar/>:<Table/>}{showTable?'Chart':'Data table'}</button></div>
      {showTable?<div className="table-scroll"><table><caption>Annual gold mine production, metric tonnes</caption><thead><tr><th>Country</th><th>{frame.year}</th><th>World share</th><th>Vs. {previous.year}</th></tr></thead><tbody>{compared.map(row=><tr key={row.id}><th><button onClick={()=>onSelect(row.id)}>{row.name}</button></th><td>{row.value}{row.estimated?' e':''}</td><td>{row.share.toFixed(1)}%</td><td>{row.delta===null?'Not covered':`${row.delta>0?'+':''}${row.delta} t`}</td></tr>)}</tbody></table></div>:<RaceChart frame={frame} selected={selected} onSelect={onSelect} reducedMotion={reducedMotion}/>}
      <Timeline index={index} onIndex={onIndex} playing={playing} onPlay={onPlay}/></div><aside className="history-notes"><h3>Production is not custody.</h3><span className="status-chip">PUBLISHED DATA · USGS</span><p>This ranking describes the world’s mined gold, independently of {asset.symbol}. It does not trace any token’s reserves to particular mines.</p><dl><div><dt>Rounded world total</dt><dd>{frame.total.toLocaleString('en-US')} t</dd></div><div><dt>Publication vintage</dt><dd>{frame.vintage}</dd></div><div><dt>Comparison year</dt><dd><select aria-label="Comparison year" value={compare} onChange={e=>setCompare(Number(e.target.value))}>{goldHistory.map((f,i)=><option key={f.year} value={i}>{f.year}</option>)}</select></dd></div></dl><p className="fine-print">2024 figures use the revised 2026 publication. 2023 uses the 2025 publication. Estimates are marked “e”. Country shares use the rounded world total, not just the displayed top 10.</p><a href={frame.source} target="_blank" rel="noreferrer">Read the original table <ArrowSquareOut/></a><button className="text-action" onClick={onShowWorld}>See this year on the globe <ArrowSquareOut/></button></aside></div>:
      <div className="market-history"><span className="status-chip">{histories.length?'OBSERVED DATA':'HOLD · NO HISTORY YET'}</span><h3>{histories.length?`${histories.length} verified observation${histories.length===1?'':'s'}`:'A timeline starts with an observation.'}</h3><p>We store complete CMC category snapshots when the running app refreshes. No backfilled or synthetic market-cap history is shown. New observations retain their original cohort and denominator.</p>{observation&&<><label>Observation <select aria-label="Market observation" value={marketIndex} onChange={e=>setMarketIndex(Number(e.target.value))}>{histories.map((h,i)=><option key={h.id} value={i}>{new Date(h.capturedAt).toLocaleString('en-US')}</option>)}</select></label><table><thead><tr><th>Token</th><th>Market cap</th><th>Covered-universe share</th></tr></thead><tbody>{observation.rows.slice(0,10).map(row=><tr key={row.id}><th>{row.name}</th><td>${Math.round(row.marketCap).toLocaleString('en-US')}</td><td>{row.share.toFixed(2)}%</td></tr>)}</tbody></table></>}<p className="fine-print">Category membership is not a backing verification. This is a token-level comparison, not the total market value of real-world gold, companies or property.</p></div>}
  </section>;
}
