import {lazy,Suspense,useEffect,useMemo,useState} from 'react';
import {Planet,MagnifyingGlass,ArrowRight,ArrowSquareOut,MapPin,ShieldCheck,FileText,Graph,GlobeHemisphereWest,ArrowsClockwise,Info,Cube,Plant,Buildings} from '@phosphor-icons/react';
import {passports,passportFor,goldHistory,goldTrade,checkedAt} from './data/research.js';
import {selectContext,safeUrl,sortRows} from './lib/domain.js';
import History,{RaceChart,Timeline} from './components/History.jsx';
import Structure from './components/Structure.jsx';
import AtlasCover from './components/AtlasCover.jsx';
const World=lazy(()=>import('./components/World.jsx'));
const usd=value=>typeof value==='number'?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:value>=1e6?'compact':'standard',maximumFractionDigits:2}).format(value):'Not available';
const layers=[{id:'production',label:'Origin & production',icon:Plant},{id:'custody',label:'Storage & custody',icon:ShieldCheck},{id:'trade',label:'Commercial context',icon:GlobeHemisphereWest}];
export function App(){
  const [assetId,setAssetId]=useState(4705),[layer,setLayer]=useState('custody'),[selected,setSelected]=useState('GBR'),[year,setYear]=useState(2),[playing,setPlaying]=useState(false),[limit,setLimit]=useState(3),[market,setMarket]=useState(null),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[focusRequest,setFocusRequest]=useState(0),[activeNav,setActiveNav]=useState('world'),[reducedMotion,setReducedMotion]=useState(false),[notice,setNotice]=useState('');
  const candidates=useMemo(()=>{const merged=new Map(passports.map(p=>[p.id,p]));for(const row of market?.rows||[])merged.set(row.id,passportFor(row));return [...merged.values()];},[market]);
  const asset=candidates.find(c=>c.id===assetId)||passports[0],frame=goldHistory[year];
  const context=useMemo(()=>selectContext(asset,layer,frame,goldTrade),[asset,layer,frame]);
  const place=context.points.find(p=>p.id===selected)||context.points[0],liveRows=(market?.rows||[]).map(passportFor),collection=liveRows.length?liveRows:passports,matches=query?candidates.filter(p=>`${p.name} ${p.symbol}`.toLowerCase().includes(query.toLowerCase())):[];
  async function refresh(){setLoading(true);try{const response=await fetch(`/api/market?limit=${limit}`);if(!response.ok)throw Error('The market data service is not available.');setMarket(await response.json());setNotice('');}catch(error){setMarket(previous=>({...previous,mode:previous?.rows?.length?'STALE':'HOLD',error:{message:error.message},rows:previous?.rows||[],history:previous?.history||[]}));}finally{setLoading(false);}}
  useEffect(()=>{refresh();const id=setInterval(()=>{if(!document.hidden)refresh();},60000);return()=>clearInterval(id);},[limit]);
  useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReducedMotion(media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
  useEffect(()=>{if(!playing)return;const id=setInterval(()=>setYear(current=>{if(current>=2){setPlaying(false);return 2;}return current+1;}),2200);return()=>clearInterval(id);},[playing]);
  useEffect(()=>{if(reducedMotion)setPlaying(false);},[reducedMotion]);
  function chooseAsset(id){navigate('world');setAssetId(id);setQuery('');setPlaying(false);const next=candidates.find(p=>p.id===id)||passports[0];setLayer(next.custody?'custody':'production');setSelected(next.custody?.id||next.origin?.id||null);setFocusRequest(v=>v+1);}
  function chooseLayer(id){setLayer(id);setPlaying(false);const next=selectContext(asset,id,frame,goldTrade);setSelected(next.points[0]?.id||null);setFocusRequest(v=>v+1);}
  function navigate(id){setActiveNav(id==='cover'?'world':id);document.getElementById(id)?.scrollIntoView({behavior:reducedMotion?'instant':'smooth',block:'start'});}
  function chooseYear(index){setYear(index);setPlaying(false);if(asset.family==='gold')setLayer('production');}
  function play(){if(playing){setPlaying(false);return;}if(asset.family!=='gold')setNotice('Gold production history is commodity context, independent of the selected equity.');if(year===2)setYear(0);if(asset.family==='gold')setLayer('production');setPlaying(true);}
  function selectCountry(id){setSelected(id);setFocusRequest(v=>v+1);}
  const inCooldown=market?.retryAt&&Date.parse(market.retryAt)>Date.now();
  return <><a className="skip-link" href="#asset-details">Skip to asset evidence</a>
    <header className="app-header"><a className="brand" href="#cover" onClick={e=>{e.preventDefault();navigate('cover');}}><Planet size={35} weight="thin"/><span>RWA Passport</span></a><span className="edition">The illustrated atlas</span><div className="search-wrap"><MagnifyingGlass size={20}/><input aria-label="Find an asset" placeholder="Find an asset" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Escape')setQuery('');if(e.key==='Enter'&&matches[0])chooseAsset(matches[0].id);}}/>{query&&<div className="search-results">{matches.length?matches.map(p=><button key={p.id} onClick={()=>chooseAsset(p.id)}><strong>{p.symbol}</strong><span>{p.name}</span></button>):<p>No match in the current collection.</p>}</div>}</div><nav aria-label="Workspace">{['world','structure','history'].map(id=><button key={id} className={activeNav===id?'active':''} onClick={()=>navigate(id)}>{id==='world'?'Overview':id[0].toUpperCase()+id.slice(1)}</button>)}</nav><div className="connection"><span className={`status-light ${market?.mode==='LIVE'?'live':''}`}/><div><strong>{loading&&!market?'CONNECTING':market?.mode==='LIVE'?'CMC LIVE':market?.mode==='STALE'?'CMC STALE':'CMC DATA HOLD'}</strong><span>{market?.capturedAt?new Date(market.capturedAt).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})+' · local time':'Official research available'}</span></div></div></header>
    <main><AtlasCover onNavigate={navigate}/><div className="collection-bar"><div className="collection-label"><span>{liveRows.length&&market.complete?'Dynamic selection':'Research collection'}</span><select aria-label="Number of ranked assets" value={limit} onChange={e=>setLimit(Number(e.target.value))}><option value={3}>Top 3</option><option value={10}>Top 10</option></select></div><div className="asset-tabs" aria-label="Select an asset">{collection.map((p,i)=><button key={p.id} aria-pressed={asset.id===p.id} onClick={()=>chooseAsset(p.id)}><span className="asset-rank">{liveRows.length?String(i+1).padStart(2,'0'):'—'}</span><strong>{p.symbol}</strong><span>{liveRows.length?usd(p.marketCap):p.category}</span></button>)}</div><button className="icon-button refresh" aria-label="Refresh market data" disabled={loading||inCooldown} onClick={refresh}><ArrowsClockwise className={loading?'spinning':''}/></button></div>
    <div className="data-notice" role="status"><Info size={15}/>{market?.mode==='LIVE'?<span>Ranked by market cap within CMC’s Tokenized Assets category · {market.eligibleCount} eligible / {market.scannedCount} scanned · {market.complete?'Complete category scan':'Partial coverage'} · token-level, not physical asset value.</span>:<span>{market?.error?.message||'Connecting to CoinMarketCap. Research passports remain available.'}{market?.retryAt?` Next provider retry after ${new Date(market.retryAt).toLocaleTimeString()}.`:''} {liveRows.length?'Last observed values are retained and marked stale.':'No current ranking or market values are being claimed.'}</span>}</div>{notice&&<div className="data-notice">{notice}<button onClick={()=>setNotice('')}>Dismiss</button></div>}
    <section id="world" className="atlas-layout" aria-label="Geographic asset explorer"><div className="globe-stage"><Suspense fallback={<div className="world-loading">Opening the atlas…</div>}><World context={context} selected={selected} onSelect={selectCountry} trade={goldTrade} focusRequest={focusRequest} reducedMotion={reducedMotion}/></Suspense><div className="map-title"><h2>Asset footprint</h2><p>{layer==='production'&&asset.family==='gold'?`Gold mine production · ${frame.year}${year===2?' estimate':''}`:layer==='trade'&&asset.family==='gold'?'U.S. gold import origins · 2021–2024':place?`${place.name} · ${place.precision||'country context'}`:'A location needs evidence.'}</p></div><div className="asset-identity">{asset.family==='gold'?<img className="gold-object" src="/assets/gold-ingot.png" alt="Illustrative unbranded gold ingot, not a photograph of token reserves"/>:<div className="equity-symbol"><Buildings size={70} weight="thin"/></div>}<div><span className="identity-kind">{asset.reference}</span><h2>{asset.symbol}</h2><p>{asset.name}</p><button className="follow-button" onClick={()=>navigate('structure')}><ArrowRight/> Follow the asset</button></div></div><div className="map-legend"><span className="legend-swatch"/>{context.kind==='quantitative'?'Stronger highlight = greater share of world production':context.kind==='trade'?'Highlighted origin countries · documented import shares':context.kind==='qualitative'?'Declared location · not a stock percentage':'No verified locations for this layer'}</div></div>
      <aside id="asset-details" className="inspector"><h2>{context.kind==='quantitative'?'Where gold comes from.':context.kind==='trade'?'Where gold moves.':'The real-world link.'}</h2><p className="inspector-intro">{asset.description}</p>
        {context.kind==='quantitative'?<><div className="inspector-label"><span>WORLD MINE PRODUCTION</span><strong>{frame.year}</strong></div><RaceChart frame={frame} selected={selected} onSelect={selectCountry} reducedMotion={reducedMotion} compact/><div className="place-focus"><span>{place?.name||'Select a country'}</span><strong>{place?.value??'—'} <small>t</small></strong><p>{place?.share?.toFixed(2)}% of rounded world total{place?.estimated?' · estimated':''}</p></div><Timeline index={year} onIndex={chooseYear} playing={playing} onPlay={play} compact/><p className="fine-print">Commodity context. Not the origin of {asset.symbol} reserves.</p><a href={frame.source} target="_blank" rel="noreferrer">USGS source table <ArrowSquareOut/></a></>:
        context.kind==='trade'?<><p className="context-notice">{goldTrade.caveat}</p><div className="location-list">{goldTrade.rows.map(p=><button key={p.id} aria-pressed={selected===p.id} onClick={()=>selectCountry(p.id)}><span>{p.name}</span><strong>{p.value}%</strong></button>)}<div><span>Other origins</span><strong>{goldTrade.otherShare}%</strong></div></div><p className="fine-print">Destination: United States. Lines connect countries schematically; they are not verified transport routes.</p><a href={goldTrade.source} target="_blank" rel="noreferrer">Official trade context <ArrowSquareOut/></a></>:
        <><dl className="asset-facts"><div><Cube/><dt>Reference asset</dt><dd>{asset.reference}</dd></div><div><Graph/><dt>Token issuer</dt><dd>{asset.issuer}</dd></div><div><MapPin/><dt>Location precision</dt><dd>{place?.precision||'Not researched'}</dd></div></dl><p className="context-notice">{context.note}</p>{place&&<button className="text-action" onClick={()=>setFocusRequest(v=>v+1)}><MapPin/> Focus {place.name}</button>}<p className="fine-print">Physical stock quantity: not loaded. No percentage of reserves is inferred.</p></>}
        <div className="sources"><h3>Official sources</h3>{asset.sources.length?asset.sources.map(source=><a key={source.id} href={safeUrl(source.url)||'#'} target="_blank" rel="noreferrer" title={source.claim}><FileText size={19}/><span>{source.label}<small>{source.publisher} · {source.kind}</small></span><ArrowSquareOut size={17}/></a>):<p>No asset-specific evidence has been researched yet. Do not infer backing from category membership.</p>}</div><p className="source-disclaimer">A source is not a guarantee of backing.<br/>Research reviewed {checkedAt}.</p></aside></section>
      <div className="layer-rail" role="group" aria-label="Geographic layers">{layers.map(l=><button key={l.id} aria-pressed={layer===l.id} onClick={()=>chooseLayer(l.id)}><l.icon size={23} weight="light"/><span>{l.label}<small>{l.id==='production'?'Understand the real-world context':l.id==='custody'?'Locate the declared backing':'Separate physical flows from token venues'}</small></span></button>)}<button onClick={()=>navigate('structure')}><Graph size={23}/><span>Evidence graph<small>Follow each relationship</small></span></button></div>
      <section className="layer-detail"><div><strong>{context.mode}</strong><p>{context.note}</p></div>{context.points.length>1&&<div className="country-options" aria-label="Accessible location selection">{sortRows(context.points).map(p=><button key={p.id} aria-pressed={selected===p.id} onClick={()=>selectCountry(p.id)}>{p.name} <span>{p.value}{context.unit==='metric tonnes'?' t':'%'}</span></button>)}</div>}</section>
      <div id="structure"><Structure key={asset.id} asset={asset} reducedMotion={reducedMotion} onLocate={id=>{chooseLayer(asset.custody?'custody':'production');selectCountry(id);navigate('world');}}/></div>
      <History asset={asset} index={year} onIndex={chooseYear} playing={playing} onPlay={play} selected={selected} onSelect={id=>{if(asset.family!=='gold')chooseAsset(4705);setLayer('production');selectCountry(id);}} reducedMotion={reducedMotion} market={market} onShowWorld={()=>{if(asset.family!=='gold')chooseAsset(4705);setLayer('production');navigate('world');}}/>
      <section className="news-section"><div className="section-heading"><div><h2>Keep the story connected.</h2><p>Curated official updates and documents. Not an automated news feed.</p></div><span className="status-chip">{asset.symbol} · source ledger</span></div>{asset.events.length?<div className="news-list">{asset.events.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(event=><article key={event.title}><time dateTime={event.date}>{new Date(event.date+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</time><div><span>{event.kind}</span><h3>{event.title}</h3><p>{event.summary}</p></div><a href={event.url} target="_blank" rel="noreferrer" aria-label={`Read source: ${event.title}`}><ArrowSquareOut size={23}/></a></article>)}</div>:<div className="empty-state"><FileText size={25}/><p>No dated official updates are curated for this asset yet. Its source documents remain available in the inspector.</p></div>}</section>
      <section className="methodology"><Info size={24}/><div><h3>What this atlas does — and does not — tell you.</h3><p>Market capitalization, mine output and custody are different measurements. Maps preserve the source’s location precision. Unknown locations stay unknown. Company headquarters are not token custody. A tokenized farm may represent land, produce or receivables: its legal instrument must establish which.</p><p>Automatic selection uses the current CMC Tokenized Assets category, filtered to fresh, positive market caps. It is not a claim to cover every RWA worldwide. New entrants appear without fabricated research. Issuer statements are attributed research, not an independent audit of backing.</p></div></section>
    </main><footer><a className="brand" href="#cover"><Planet size={26}/><span>RWA Passport</span></a><span>Independent prototype · Not affiliated with CoinMarketCap.</span><a href="/api-proof.html">API proof</a><a href="/demo.html">Video demo</a><a href="https://coinmarketcap.com/" target="_blank" rel="noreferrer">Market data by CoinMarketCap <ArrowSquareOut/></a><p className="atlas-art-credit">Illustrations are an imagined landscape, created with AI. Locations, market values and source documents belong to the research layers. <a href="/assets/atlas-landscape-v2.provenance.json">Artwork provenance</a></p></footer>
  </>;
}

